* generate-feeder  - description

** Usage
ChatGPT projects have a file limit of 20 files, each at 50MB in size. I am in the process of worldbuilding two different worlds. I manage my projects in Emacs org-mode. I have a navbar.org file that contains all the navigation needed for the site. This program executes some regex on the navbar.org to create a new org-mode file that includes all the site's files rather than just link to them. Then I convert to Markdown in Emacs and I have a single markdown file with all my site's webpages I can use as a project file with ChatGPT.

Usage is as simple as
#+begin_src shell
generate-feeder navbar.org metafile-feeder.org
#+end_src

Emacs is best suited for the conversion to Markdown as it will automatically inject all the other files into the feeder file.

** Installation
Easiest way to build is to use [[https://github.com/takagi/lake][lake]].
#+begin_src shell
git clone https://github.com/timotheosh/generate-feeder.git
cd generate-feeder
lake
cp target/generate-feeder ${HOME}/.local/bin/
#+end_src
** Author

+ Tim Hawes <trhawes@gmail.com>

** Copyright

Copyright (c) 2025 Tim Hawes <trhawes@gmail.com>

** License

Licensed under the MIT License.
